version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: surdurulebilir-postgres
    environment:
      POSTGRES_DB: surdurulebilir_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - surdurulebilir_postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: surdurulebilir-app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://admin:admin123@postgres:5432/surdurulebilir_db

volumes:
  surdurulebilir_postgres_data:
